version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: VoN
      MONGO_INITDB_ROOT_PASSWORD: NoV
      MONGO_INITDB_DATABASE: experiments
  mongo-seed:
    container_name: mongo-seed
    build: .
    restart: on-failure:10
    depends_on:
     - mongo
    links:
      - mongo
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: VoN
      ME_CONFIG_MONGODB_ADMINPASSWORD: NoV