version: '3.1'
services:
  # MongoDB service.
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: VoN
      MONGO_INITDB_ROOT_PASSWORD: NoV
      MONGO_INITDB_DATABASE: experiments
  # MongoDB populate service.
  mongo-seed:
    container_name: mongo-seed
    build: 
      context: mongo/.
    restart: on-failure:10
    depends_on:
     - mongo
    links:
     - mongo
  # MongoDB administration service.
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: VoN
      ME_CONFIG_MONGODB_ADMINPASSWORD: NoV
  # Golang API service.
  api:
    build: 
      context: go/.
    container_name: api
    environment:
      MONGOURL: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: experiments
      MONGO_INITDB_ROOT_USERNAME: VoN
      MONGO_INITDB_ROOT_PASSWORD: NoV
    restart: on-failure:10
    depends_on:
     - mongo
    links:
     - mongo
    ports:
     - 3000:3000